# Generated by Django 5.1.15 on 2026-04-13 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source_file', models.CharField(help_text='원본 파일명 (예: p1 1. 인공지능과 기계학습 (Revised).pdf)', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('is_indexed', models.BooleanField(default=False, help_text='FAISS 벡터 인덱스 반영 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LectureSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(help_text='구간 시작 시간 (HH:MM:SS 또는 MM:SS)', max_length=20)),
                ('end_time', models.CharField(help_text='구간 종료 시간', max_length=20)),
                ('transcript', models.TextField(help_text='STT 변환 텍스트')),
                ('embedding_id', models.IntegerField(blank=True, help_text='FAISS 인덱스 내 벡터 ID', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='lectures.lecture')),
            ],
            options={
                'ordering': ['lecture', 'start_time'],
            },
        ),
    ]
