# Generated by Django 5.1.15 on 2026-04-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='사용자 프롬프트')),
                ('query_type', models.CharField(choices=[('search', '구간 검색'), ('summary', '요약'), ('recommend', '추천')], default='search', max_length=20)),
                ('model_name', models.CharField(help_text='사용할 Ollama 모델 키 (예: qwen, llama)', max_length=100)),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('processing', '처리 중'), ('completed', '완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('task_id', models.CharField(blank=True, help_text='Celery 태스크 ID', max_length=255, null=True)),
                ('result_text', models.TextField(blank=True, default='')),
                ('retrieved_segments', models.JSONField(blank=True, default=list, help_text='RAG로 검색된 세그먼트 정보')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'LLM 쿼리',
                'verbose_name_plural': 'LLM 쿼리들',
                'ordering': ['-created_at'],
            },
        ),
    ]
