# Generated by Django 5.1.15 on 2026-04-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmquery',
            name='grounding',
            field=models.JSONField(blank=True, default=dict, help_text='Grounded RAG 검증 결과 (faithfulness, citation 정보)'),
        ),
    ]
